BEGIN;
DROP TRIGGER submit_references_export ON ati_request_events;
DROP FUNCTION submit_must_reference_export();
DROP TRIGGER append_only_ati_intake_source_acceptances ON ati_intake_source_acceptances;
DROP TRIGGER append_only_ati_response_intakes ON ati_response_intakes;
DROP TRIGGER append_only_ati_responses ON ati_responses;
DROP TRIGGER append_only_ati_request_events ON ati_request_events;
DROP TRIGGER append_only_ati_request_revisions ON ati_request_revisions;
DROP FUNCTION reject_ati_mutation();
DROP TABLE ati_intake_source_acceptances;
DROP TABLE ati_response_intakes;
DROP TABLE ati_responses;
DROP TABLE ati_request_events;
DROP TABLE ati_request_revisions;
ALTER TABLE ati_requests ALTER COLUMN received_source_ids SET NOT NULL;
ALTER TABLE ati_requests ALTER COLUMN public_interest_context SET NOT NULL;
ALTER TABLE ati_requests ALTER COLUMN requested_records SET NOT NULL;
ALTER TABLE ati_requests ALTER COLUMN holding_institution SET NOT NULL;
ALTER TABLE ati_requests ALTER COLUMN drafted_at SET NOT NULL;
ALTER TABLE ati_requests ALTER COLUMN status SET NOT NULL;
COMMIT;
