'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Check, Clipboard, Download, ExternalLink, FileText, Share2 } from 'lucide-react'
import { AppShell } from '@/components/layout/app-shell'
import { buildAtiDraft, buildGapShareText, copyText, downloadText, gapRecords, isAtiPath, resolutionPathLabels, type GapRecord, type ResolutionPath } from '@/lib/types/gaps'

const lineage = ['Claim', 'Unresolved finding', 'Gap', 'What would settle it', 'Likely holder']

export function GapDetail({ id = 'GAP-001' }: { id?: string }) {
  const initial = gapRecords.find((gap) => gap.id === id) ?? gapRecords[0]
  const [gap, setGap] = useState(initial)
  const [copied, setCopied] = useState(false)
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState(() => buildAtiDraft(initial))
  const [shared, setShared] = useState(false)
  const ati = isAtiPath(gap.resolutionPath)
  const shareText = useMemo(() => buildGapShareText(gap), [gap])

  async function handleCopy(text: string) { await copyText(text); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }

  return <AppShell><div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
    <Link href={`/xray/XRAY-KE-001`} className="mb-8 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Back to evidence explorer</Link>
    <header className="border-b border-border pb-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-primary">Gap → action · {gap.id}</p><h1 className="mt-3 max-w-3xl text-3xl font-semibold tracking-tight md:text-5xl">{gap.title}</h1><p className="mt-4 max-w-2xl text-muted-foreground">A missing document is structured product state, not research failure.</p></div><span className="rounded-full border border-amber-500/40 bg-amber-500/10 px-3 py-1 font-mono text-[10px] uppercase tracking-wider text-amber-200">{gap.status}</span></div>
      <div className="mt-8 flex flex-wrap gap-2">{[...lineage, ...(ati ? ['ATI draft'] : ['Next record'])].map((item, index) => <span key={item} className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{index > 0 && <span className="text-primary">→</span>}{item}</span>)}</div>
    </header>

    <main className="grid gap-8 py-10 lg:grid-cols-[1fr_300px]">
      <div className="flex min-w-0 flex-col gap-6">
        <section className="rounded-2xl border border-border bg-card p-6"><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">What is missing?</p><p className="mt-3 text-xl leading-relaxed text-foreground">{gap.missing}</p><div className="mt-6 border-t border-border pt-5"><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Why it matters</p><p className="mt-3 leading-7 text-muted-foreground">{gap.whyItMatters}</p></div></section>
        <section className="rounded-2xl border border-primary/30 bg-primary/5 p-6"><div className="flex items-center justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-widest text-primary">What would settle it?</p><h2 className="mt-2 text-2xl font-semibold text-foreground">A current authoritative bridge</h2></div><FileText className="size-6 text-primary" /></div><ul className="mt-5 grid gap-3 sm:grid-cols-2">{gap.settleIt.map((item) => <li key={item} className="flex gap-3 text-sm text-muted-foreground"><Check className="mt-0.5 size-4 shrink-0 text-primary" />{item}</li>)}</ul></section>
        <section className="rounded-2xl border border-border bg-card p-6"><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Resolution path</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{(Object.keys(resolutionPathLabels) as ResolutionPath[]).map((path) => <button key={path} onClick={() => setGap({ ...gap, resolutionPath: path })} className={`rounded-xl border px-4 py-3 text-left text-sm transition-colors ${gap.resolutionPath === path ? 'border-primary bg-primary/10 text-foreground' : 'border-border text-muted-foreground hover:border-primary/50'}`}>{resolutionPathLabels[path]}{path === 'PUBLIC_RECORD_REQUEST' && <span className="mt-1 block font-mono text-[9px] uppercase text-primary">ATI draft available</span>}</button>)}</div></section>
        {ati ? <section className="rounded-2xl border border-border bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-widest text-primary">Draft request</p><h2 className="mt-2 text-2xl font-semibold">Build from the evidence trail</h2><p className="mt-2 text-sm text-muted-foreground">Assembled from the claim, unresolved finding, gap, and settling evidence above. Not submitted by X-Ray.</p></div><div className="flex gap-2"><button onClick={() => handleCopy(draft)} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-medium hover:bg-muted"><Clipboard className="size-4" />{copied ? 'Copied' : 'Copy'}</button><button onClick={() => downloadText(`${gap.id.toLowerCase()}-draft.txt`, draft)} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-medium hover:bg-muted"><Download className="size-4" />Download</button></div></div><div className="mt-5 rounded-xl border border-border bg-background p-5"><div className="mb-4 flex items-center justify-between"><span className="rounded-full bg-primary/10 px-2 py-1 font-mono text-[9px] uppercase tracking-wider text-primary">Draft request · Kenya ATI framework</span><button onClick={() => setEditing(!editing)} className="text-xs text-muted-foreground underline underline-offset-4">{editing ? 'Preview' : 'Edit draft'}</button></div>{editing ? <textarea value={draft} onChange={(event) => setDraft(event.target.value)} className="min-h-80 w-full resize-y rounded-lg border border-border bg-card p-4 font-mono text-xs leading-6 text-foreground outline-none focus:border-primary" aria-label="Editable ATI draft" /> : <pre className="whitespace-pre-wrap font-mono text-xs leading-6 text-muted-foreground">{draft}</pre>}</div></section> : <section className="rounded-2xl border border-border bg-card p-6"><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Next step</p><h2 className="mt-2 text-2xl font-semibold">{resolutionPathLabels[gap.resolutionPath]}</h2><p className="mt-3 leading-7 text-muted-foreground">This gap should not automatically produce an information request. The next useful evidence is listed above; X-Ray is waiting for a public record or a future update.</p></section>}
        <section className="rounded-2xl border border-border bg-muted/30 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Responsible share</p><h2 className="mt-2 text-xl font-semibold">X-Ray found a missing receipt</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">This gap does not imply wrongdoing. It describes what is missing and what would settle the question.</p></div><button onClick={async () => { await handleCopy(shareText); setShared(true) }} className="inline-flex items-center gap-2 rounded-lg bg-foreground px-4 py-2 text-sm font-semibold text-background"><Share2 className="size-4" />{shared ? 'Share text copied' : 'Share gap'}</button></div></section>
      </div>
      <aside className="flex flex-col gap-5"><section className="rounded-2xl border border-border bg-card p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Likely record holder</p><h2 className="mt-3 text-lg font-semibold leading-6">{gap.holder}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{gap.holderNote}</p></section><section className="rounded-2xl border border-border bg-card p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Investigation context</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{gap.context}</p><div className="mt-5 border-t border-border pt-4"><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Identifiers</p><ul className="mt-3 flex flex-col gap-2">{gap.identifiers.map((item) => <li key={item} className="text-xs text-foreground">{item}</li>)}</ul></div></section><Link href="/library" className="inline-flex items-center justify-between rounded-xl border border-border px-4 py-3 text-sm font-medium hover:bg-muted">View cached X-Rays <ExternalLink className="size-4 text-muted-foreground" /></Link></aside>
    </main>
  </div></AppShell>
}
